# The onramp and offramp sections of configuration specify external sources and sinks
# to an instance of tremor server.
#
onramp:
  - id: data-input
    type: blaster
    codec: json
    config:
      source: /data/input.json
      interval: core::datetime::from_millis(10)

offramp:
  - id: kafka-out
    type: kafka
    codec: json
    config:
      group_id: kafka-feeder
      brokers:
        - kafka:9092
      topic: tremor
