onramp:
  - id: ws
    type: ws
    linked: true
    codec: string
    preprocessors:
      - lines
    config:
      host: 0.0.0.0
      port: 8139

binding:
  - id: main
    links:
      "/onramp/ws/{instance}/out": ["/pipeline/echo/{instance}/in"]
      "/pipeline/echo/{instance}/out": ["/onramp/ws/{instance}/in"]
      "/pipeline/echo/{instance}/err": ["/offramp/system::stderr/system/in"]

mapping:
  /binding/main/01:
    instance: "01"
