version: "3.3"
services:
  zookeeper:
    image: "wurstmeister/zookeeper:3.4.6"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.2.0"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "tremor:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka_feeder:
    # enable once https://github.com/tremor-rs/tremor-runtime/pull/759 lands
    # on latest release
    #image: tremorproject/tremor:latest
    image: tremorproject/tremor:edge
    depends_on:
      - kafka
    environment:
      - SLEEP=10
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./kafka_feeder/etc/tremor:/etc/tremor:ro
      - ./kafka_feeder/logs:/logs:rw
      - ./data:/data:ro
  tremor:
    image: tremorproject/tremor:edge
    depends_on:
      - kafka
    environment:
      - SLEEP=2
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor:/etc/tremor:ro
      - ./logs:/logs:rw
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    environment:
      # also set the vm.max_map_count kernel setting for production use. See:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # elasticsearch-specific xpack features (to be used when xpack is installed)
      # disable these when using the elasticsearch-oss image
      - xpack.license.self_generated.type=basic
      - xpack.monitoring.collection.enabled=false
      - discovery.type=single-node
      - action.auto_create_index=true
    ulimits:
      # disabling swapping for performance and node stability
      memlock:
        soft: -1
        hard: -1
    volumes:
      # share the config in the repo with the container
      - ./etc/elasticsearch/:/etc/elasticsearch:rw
      # using local docker volume for es data
      # gets stored in /var/lib/docker/volumes by default, and can specify a
      # custom path here, but need to configure the dir perms for container use
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esdata:
    driver: local