version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    environment:
      # also set the vm.max_map_count kernel setting for production use. See:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # elasticsearch-specific xpack features (to be used when xpack is installed)
      # disable these when using the elasticsearch-oss image
      - xpack.license.self_generated.type=basic
      - xpack.monitoring.collection.enabled=false
      - discovery.type=single-node
    ulimits:
      # disabling swapping for performance and node stability
      memlock:
        soft: -1
        hard: -1
    volumes:
      # share the config in the repo with the container
      - ./etc/elasticsearch/:/etc/elasticsearch:rw
      # using local docker volume for es data
      # gets stored in /var/lib/docker/volumes by default, and can specify a
      # custom path here, but need to configure the dir perms for container use
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esdata:
    driver: local
