scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 20s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 20s
    static_configs:
    - targets: ['prompush:9091']
