onramp:
  - id: metronome
    type: metronome
    config:
      interval: 1000 # Every second

offramp:
  - id: ws
    type: ws
    config:
      url: ws://0.0.0.0:8080/

binding:
  - id: default
    links:
      "/onramp/metronome/{instance}/out":
        ["/pipeline/transient_gd/{instance}/in"]
      "/pipeline/transient_gd/{instance}/out": ["/offramp/ws/{instance}/in"]

mapping:
  /binding/default/01:
    instance: "01"
