version: "3.3"
services:
  zookeeper:
    image: "wurstmeister/zookeeper:3.4.6"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.2.0"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "tremor:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  tremor_in:
    image: tremorproject/tremor:latest
    depends_on:
      - kafka
    environment:
      - SLEEP=10
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./logs:/logs:rw
      - ./data:/data:ro
  tremor_out:
    image: tremorproject/tremor:latest
    depends_on:
      - kafka
    environment:
      - SLEEP=20
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log:/var/log:rw
      - ./data:/data:ro
