pipeline:
  - id: postgres-things
    interface:
      inputs: [ in ]
      outputs: [ out ]
    nodes:
      - id: script
        op: runtime::tremor
        config:
          script: |
            event
    links:
      in: [ script ]
      script: [ out ]
  - id: crononome-things
    interface:
      inputs: [ in ]
      outputs: [ out ]
    nodes:
      - id: script
        op: runtime::tremor
        config:
          script: |
            event.trigger.payload
    links:
      in: [ script ]
      script: [ out ]
