binding:
  - id: thinger
    links:
      '/onramp/postgres-input/{instance}/out': [ '/pipeline/postgres/{instance}/in' ]
      '/onramp/crononome-input/{instance}/out': [ '/pipeline/crononome/{instance}/in' ]
      '/pipeline/postgres/{instance}/out': [ '/offramp/timescaledb-output/{instance}/in', '/offramp/system::stdout/{instance}/in' ]
      '/pipeline/crononome/{instance}/out': [ '/offramp/timescaledb-output/{instance}/in', '/offramp/system::stdout/{instance}/in' ]
