version: "3.8"

services:
  tremor-server:
    image: tremorproject/tremor:0.11
    ports:
      - 9898:9898
      - 8139:8139
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ../31_servers_lt_ws/etc/tremor:/etc/tremor:ro
      - ../31_servers_lt_ws/var/log:/var/log:rw
  tremor-bridge:
    image: tremorproject/tremor:0.11
    depends_on:
      - tremor-server
    ports:
      - 9899:9898
      - 9139:9139
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ./etc/tremor:/etc/tremor:rw
      - ./var/log:/var/log:rw
