version: '3.8'
services:
  influxdb:
    image: influxdb:1.7
    ports:
      - '8086:8086'
      - '8083:8083'
    environment:
      INFLUXDB_DB: 'tremor'
  chronograf:
    image: chronograf:1.7
    ports:
      - '8888:8888'
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:1.11
    depends_on:
      - influxdb
      - tremor
    volumes:
      - ./etc/telegraf:/etc/telegraf:ro
  tremor:
    image: tremorproject/tremor:0.11
    depends_on:
      - influxdb
    ports:
      - 4242:4242
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor:/etc/tremor:ro
      - ./var/log:/var/log:rw