version: "3.7"

services:
  tremor:
    image: tremorproject/tremor:${TREMOR_VERSION}
    environment:
      - RUST_BACKTRACE=full
      - TREMOR_PATH=/opt/local/tremor/lib:/etc/tremor/lib
    volumes:
      - ./etc/tremor:/etc/tremor:rw
      - ./var/log:/var/log:rw
    ports:
      - 9898:9898   # tremor api
      - 12202:12202 # log receiver
      - 8139:8139 # quota service

  elasticsearch:
    image: docker.elastic.co/elasticsearch/${ES_IMAGE}:${ES_VERSION}
    environment:
      # also set the vm.max_map_count kernel setting for production use. See:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
      - "ES_JAVA_OPTS=-Xms${ES_JAVA_HEAP_SIZE} -Xmx${ES_JAVA_HEAP_SIZE}"
      # elasticsearch-specific xpack features (to be used when xpack is installed)
      # disable these when using the elasticsearch-oss image
      - xpack.license.self_generated.type=basic
      - xpack.monitoring.collection.enabled=false
    ulimits:
      # disabling swapping for performance and node stability
      memlock:
        soft: -1
        hard: -1
    volumes:
      # share the config in the repo with the container
      - ./etc/elasticsearch/:/etc/elasticsearch:rw
      # using local docker volume for es data
      # gets stored in /var/lib/docker/volumes by default, and can specify a
      # custom path here, but need to configure the dir perms for container use
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/${KIBANA_IMAGE}:${KIBANA_VERSION}
    depends_on:
      - elasticsearch
    environment:
      # limit kibana memory usage (default is 1G)
      - "NODE_OPTIONS=--max-old-space-size=${KIBANA_NODE_MEM_LIMIT_MB}"
      # for valid options here, see:
      # https://github.com/elastic/kibana-docker/blob/master/build/kibana/bin/kibana-docker
      # if true, only error messages are shown
      - LOGGING_QUIET=${KIBANA_LOGGING_QUIET}
      # which page to launch by default
      - KIBANA_DEFAULTAPPID=discover
      # kibana-specific xpack features (to be used when xpack is installed)
      - XPACK_LICENSE_SELF_GENERATED_TYPE=basic
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
