# The onramp and offramp sections of configuration specify external sources and sinks
# to an instance of tremor server.
#
onramp:
  - id: udp-input # A unique id for binding/mapping
    type: udp # The unique type descriptor for the onramp ( websocket server here)
    codec: influx # The underlying data format expected for application payload data
    preprocessors: # telegraf udp sends multiple influx line messages in one package seperated by new lines
      - lines
    config:
      port: 4242 # The UDP port to listen on
      host: "0.0.0.0" # The IP address to bind on ( all interfaces in this case )
  - id: tick
    type: metronome
    config:
      interval: 10000

offramp:
  - id: influx-output
    type: rest # an influxdb offramp
    codec: influx
    postprocessors:
      - lines
    config:
      endpoint:
        host: influxdb
        port: 8086
        path: /write
        query: db=tremor
        headers:
          "Client": "Tremor"
  - id: influx-query
    type: rest
    codec: json
    linked: true
    config:
      endpoint:
        host: influxdb
        port: 8086
        path: /query
      headers:
        "Client": "Tremor"
        "Accept": "application/json"
      method: GET
